-- Converts a clone of the India production database into a Saudi base.
-- Run against the SAUDI database only. Never against qubix.
--   mysql -uroot -p qubix_sa < scripts/convert-to-saudi.sql
--
-- Replace <SAUDI_DOMAIN> before running.
--
-- Table list verified against the actual schema (2026-08-31), not just the
-- headline names — every table with a foreign key into orders/customers/cart
-- is included, not just the ones a name search turns up. Two tables named in
-- earlier drafts don't exist and are intentionally omitted:
--   - `order_address`: order addresses live in the shared `addresses` table
--     (customer_id/cart_id/order_id + address_type columns), already covered
--     by the wholesale `TRUNCATE TABLE addresses` below.
--   - `sessions`: this app runs SESSION_DRIVER=redis (both here and in
--     .env.production.example), so sessions are Redis keys, never MySQL rows
--     — there is nothing to truncate in a mysqldump either database produces.

SET FOREIGN_KEY_CHECKS = 0;

-- 1. Orders and everything with a foreign key into orders.id. None of it
--    belongs to the new store.
TRUNCATE TABLE order_comments;
TRUNCATE TABLE order_items;
TRUNCATE TABLE order_payment;
TRUNCATE TABLE order_transactions;
TRUNCATE TABLE notifications;              -- every row here is an order notification (order_id NOT NULL)
TRUNCATE TABLE invoice_items;
TRUNCATE TABLE invoices;
TRUNCATE TABLE shipment_items;
TRUNCATE TABLE shipments;
TRUNCATE TABLE refund_items;
TRUNCATE TABLE refunds;
TRUNCATE TABLE downloadable_link_purchased; -- also has customer_id, see below
TRUNCATE TABLE bookings;                    -- also has product_id, see below
TRUNCATE TABLE orders;

-- 2. Customers and everything with a foreign key into customers.id.
TRUNCATE TABLE cart_rule_coupon_usage;
TRUNCATE TABLE cart_rule_customers;
TRUNCATE TABLE compare_items;
TRUNCATE TABLE customer_notes;
TRUNCATE TABLE customer_social_accounts;
TRUNCATE TABLE gdpr_data_request;
TRUNCATE TABLE wishlist_items;
TRUNCATE TABLE wishlist;
TRUNCATE TABLE subscribers_list;
TRUNCATE TABLE cart_payment;
TRUNCATE TABLE cart_shipping_rates;
TRUNCATE TABLE cart_items;
TRUNCATE TABLE cart;
TRUNCATE TABLE addresses;                   -- covers customer_id, cart_id, AND order_id addresses
TRUNCATE TABLE customers;
TRUNCATE TABLE visits;
TRUNCATE TABLE search_terms;

-- 3. Placeholder catalogue and everything with a foreign key into products.id.
--    Every product currently in the India database was created while testing
--    the admin panel, and its prices are rupee numbers. Cloning them into a
--    SAR store would relabel INR figures as SAR. The client enters real Saudi
--    products instead. Category/attribute STRUCTURE is deliberately kept —
--    see the header note above and the design doc.
TRUNCATE TABLE product_reviews;
TRUNCATE TABLE product_videos;
TRUNCATE TABLE product_super_attributes;
TRUNCATE TABLE product_cross_sells;
TRUNCATE TABLE product_relations;
TRUNCATE TABLE product_up_sells;
TRUNCATE TABLE product_grouped_products;
TRUNCATE TABLE product_downloadable_samples;
TRUNCATE TABLE product_downloadable_links;
TRUNCATE TABLE product_customizable_options;
TRUNCATE TABLE product_customer_group_prices;
TRUNCATE TABLE product_bundle_option_products;
TRUNCATE TABLE product_bundle_options;
TRUNCATE TABLE booking_products;
TRUNCATE TABLE product_ordered_inventories;
TRUNCATE TABLE catalog_rule_product_prices;  -- computed index, regenerated by catalog-rule:index
TRUNCATE TABLE catalog_rule_products;        -- computed index, regenerated by catalog-rule:index
TRUNCATE TABLE product_attribute_values;
TRUNCATE TABLE product_flat;
TRUNCATE TABLE product_categories;
TRUNCATE TABLE product_channels;
TRUNCATE TABLE product_inventories;
TRUNCATE TABLE product_price_indices;
TRUNCATE TABLE product_inventory_indices;
TRUNCATE TABLE product_images;
TRUNCATE TABLE products;

-- 4. Currency: SAR becomes the base.
INSERT INTO currencies (code, name, symbol, `decimal`, group_separator, decimal_separator)
SELECT 'SAR', 'Saudi Riyal', 'SAR', 2, ',', '.'
WHERE NOT EXISTS (SELECT 1 FROM currencies WHERE code = 'SAR');

-- 5. Locale: Arabic must exist and be RTL.
INSERT INTO locales (code, name, direction)
SELECT 'ar', 'Arabic', 'rtl'
WHERE NOT EXISTS (SELECT 1 FROM locales WHERE code = 'ar');

-- 6. Point the channel at the Saudi domain, currency and locale.
UPDATE channels
SET hostname          = 'https://<SAUDI_DOMAIN>',
    base_currency_id  = (SELECT id FROM currencies WHERE code = 'SAR'),
    default_locale_id = (SELECT id FROM locales    WHERE code = 'ar'),
    timezone          = 'Asia/Riyadh'
WHERE id = 1;

-- channels.code stays 'default': config('app.channel') expects it and
-- ChannelController::destroy()'s guard both expect that value.
-- Separate DB, so no collision.

DELETE FROM channel_currencies WHERE channel_id = 1;
INSERT INTO channel_currencies (channel_id, currency_id)
SELECT 1, id FROM currencies WHERE code = 'SAR';

-- Arabic-only storefront by default — a language switcher is only worth having
-- if someone commits to maintaining two full sets of translated content
-- indefinitely. Absent that commitment, a partially-translated second language
-- looks worse than not offering one (already found and fixed once on India's
-- own Arabic test channel — see docs/bugs.md). If the client confirms a
-- bilingual (ar+en) storefront instead, change the WHERE clause below to:
--   WHERE code IN ('ar', 'en')
DELETE FROM channel_locales WHERE channel_id = 1;
INSERT INTO channel_locales (channel_id, locale_id)
SELECT 1, id FROM locales WHERE code = 'ar';

-- 7. Config rows that named the India channel or its addresses.
DELETE FROM core_config WHERE code LIKE 'sales.payment_methods.%';
DELETE FROM core_config WHERE code LIKE 'general.content.%';

SET FOREIGN_KEY_CHECKS = 1;

SELECT 'channel'   AS item, hostname AS value FROM channels WHERE id = 1
UNION ALL SELECT 'currency', c.code FROM currencies c
    JOIN channels ch ON ch.base_currency_id = c.id WHERE ch.id = 1
UNION ALL SELECT 'locale', l.code FROM locales l
    JOIN channels ch ON ch.default_locale_id = l.id WHERE ch.id = 1
UNION ALL SELECT 'products', CAST(COUNT(*) AS CHAR) FROM products
UNION ALL SELECT 'orders', CAST(COUNT(*) AS CHAR) FROM orders
UNION ALL SELECT 'customers', CAST(COUNT(*) AS CHAR) FROM customers;
